{-# LANGUAGE BlockArguments #-}
module Random where
import Control.Monad.Random
import Graphics.Vec3
import Control.Monad.Loops
import qualified Interval as I
import System.Random.SplitMix (mkSMGen, nextDouble)
import Data.Bits (xor)
import GHC.Float (castDoubleToWord64)
import System.Random.Stateful

-- | hash function rng from ray data, large prime are from FNV/xxHash family,
-- generated by ai, did not check randomness dont use for security
hashToFloat01 :: V3 -> V3 -> Double -> Double
hashToFloat01 (V3 ox oy oz) (V3 dx dy dz) t =
  let seed = castDoubleToWord64 ox `xor` castDoubleToWord64 oy * 2654435761
          `xor` castDoubleToWord64 oz * 2246822519
          `xor` castDoubleToWord64 dx * 3266489917
          `xor` castDoubleToWord64 dy * 668265263
          `xor` castDoubleToWord64 dz * 374761393
          `xor` castDoubleToWord64 t  * 1640531513
      gen  = mkSMGen seed
  in fst (nextDouble gen)

-- | Returns a vector to a random point in the [-.5,-.5]-[+.5,+.5] unit square on viewport
-- | per documentation, the range of random of Doubles lies in [0, 1)
{-# INLINE getSampleSquare #-}
getSampleSquare :: StatefulGen g m => g -> m V3
getSampleSquare gen = liftM3 V3 (uniformRM (-0.5, 0.5) gen) (uniformRM (-0.5, 0.5) gen) (pure 0)

-- | returns a unit cube vector
{-# INLINE getRandomVec #-}
getRandomVec :: StatefulGen g m => (Double, Double) -> g -> m V3
getRandomVec range gen = liftM3 V3 (uniformRM range gen) (uniformRM range gen) (uniformRM range gen)

-- | return a unit sphere vector, by rejection method
-- | ie keep finding until the normalized vector is within sphere
{-# INLINE getRandomUnitVec #-}
getRandomUnitVec :: StatefulGen g m => g -> m V3
getRandomUnitVec gen = (\x -> x ./ sqrt (lengthSquared x)) <$> iterateUntil inUnitBall (getRandomVec (-1, 1) gen)
  where
    inUnitBall = I.contains (I.Interval 1e-160 1) . lengthSquared

{-# INLINE getRandomInUnitDisk #-}
getRandomInUnitDisk :: StatefulGen g m => g -> m V3
getRandomInUnitDisk gen = iterateUntil inUnitDisk (liftM3 V3 (uniformRM (-1, 1) gen) (uniformRM (-1, 1) gen) (pure 0))
  where
    inUnitDisk = I.contains (I.Interval 1e-160 1) . lengthSquared

-- {-# INLINE getRandomDouble #-}
-- getRandomDouble :: Rand StdGen Double
-- -- | getRandomDouble = getRandomR (0, 1)
-- getRandomDouble = getRandom